version: 3

silent: true

includes:
  terraform:
    internal: true
    taskfile: ./terraform

  terragrunt:
    internal: true
    taskfile: ./terragrunt

  tflint:
    internal: true
    taskfile: ./tflint

tasks:
  init:
    desc: Initialize shims
    cmds:
      - echo 'Initializing terraform...'
      - task: terraform:init

      - echo 'Initializing terragrunt...'
      - task: terragrunt:init

      - echo 'Initializing tflint...'
      - task: tflint:init

  clean:
    desc: Clean shims
    cmds:
      - echo 'Cleaning terraform...'
      - task: terraform:clean

      - echo 'Cleaning terragrunt...'
      - task: terragrunt:clean

      - echo 'Cleaning tflint...'
      - task: tflint:clean
