sources:
  dotenv:
    class_name: DotEnvSource
    init_args:
      file_path: .env
  yc_lockbox_tfstate:
    class_name: YCCLILockboxSource
    init_args:
      profile: $sources[dotenv][YC_PROFILE]
      folder: tfstate
      lockbox: tfstate_bucket_keys
collections:
  local:
    init_args:
      AWS_ACCESS_KEY_ID:
        source: $sources[yc_lockbox_tfstate]
        key: ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        source: $sources[yc_lockbox_tfstate]
        key: SECRET_ACCESS_KEY
transfers:
  local:
    init_args:
      collection: $collections[local]
      destination: $destinations[bash_export]
