# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket                      = "ovsds-example-cloud-tfstate"
    endpoint                    = "https://storage.yandexcloud.net"
    key                         = "environments/github/iac/terraform.tfstate"
    region                      = "ru-central1"
    skip_credentials_validation = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
  }
}
